In [1]:
import tensorflow as tf

import numpy as np
import IPython.display as display

In [2]:
a = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [3]:
for i in a:
    print(i)

[1 2 3 4]
[5 6 7 8]
[ 9 10 11 12]


In [7]:
a[a%10==0]

array([10])

In [8]:
a/10

array([[0.1, 0.2, 0.3, 0.4],
       [0.5, 0.6, 0.7, 0.8],
       [0.9, 1. , 1.1, 1.2]])

In [9]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [10]:
(a > 5)

array([[False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True]])